#!/usr/bin/env bash
# installing nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html
sudo sed -i "s/\tlisten [0-9].* default_server;*/\tlisten 80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/\tlisten \[::\]:[0-9].* default_server;*/\tlisten [::]:80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i "s/\tlisten [0-9].* default_server;*/\tlisten 80 default_server;/" /etc/nginx/sites-available/default
sudo sed -i "s/\tlisten \[::\]:[0-9].* default_server;*/\tlisten [::]:80 default_server;/" /etc/nginx/sites-available/default
sudo service nginx start
