#!/usr/bin/env bash
# Configures an Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen thelaura' /etc/haproxy/haproxy.cfg
sed -i '/listen thelaura/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 652-web-01 44.210.106.133 check' /etc/haproxy/haproxy.cfg
sed -i '/server 652-web-01 44.210.106.133 check/a         server 652-web-02 3.227.251.74 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
