#!/usr/bin/env bash
# what is keeping your Ubuntu container’s Nginx installation from listening on port 80?
# configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
