#!/usr/bin/env bash
#prints a string 10 times
j=0
while [ $j != 11 ]
do
  if [ $j = 4 ]
  then
    echo "bad luck"
  elif [ $j = 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  j=$(( j + 1 ))
done
