#!/usr/bin/env bash
# Change localhost to 127.0.02
# Change facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.2    localhost/g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
